Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,43 +1,42 @@
-name: Run daku Workflow
+name: Auto Restart and Keep Codespace Active
 
 on:
-  push:
-    branches:
-      - main
   schedule:
-    - cron: '*/30 * * * *'
-
-concurrency:
-  group: run_daku_workflow
+    - cron: '* * * * *'  # Runs every minute
+  workflow_dispatch:
 
 jobs:
-  run_daku_workflow:
-    runs-on: macos-latest 
+  restart_codespace:
+    runs-on: ubuntu-latest
 
     steps:
-      - name: Check out the code
-        uses: actions/checkout@v2
-
-      - name: binary by @daku
-        run: chmod +x daku
-
-      - name: Set up Python
-        uses: actions/setup-python@v3
-        with:
-          python-version: '3.x'
-
-      - name: Install required packages
+      - name: Install GitHub CLI if not present
         run: |
-          pip install python-telegram-bot --upgrade
-          pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot
-          pip install telebot pymongo aiohttp psutil
-          pip install motor
-          pip install nest_asyncio
-          pip install pytz
+          if ! command -v gh &> /dev/null; then
+            sudo apt-get install gh jq
+          fi
 
-      - name: Run daku.py
-        env:
-          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
-          MONGO_URI: ${{ secrets.MONGO_URI }}
-        run: python3 daku.py
-        
+      - name: Authenticate GitHub CLI with Personal Access Token
+        run: |
+          echo "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" | gh auth login --with-token
+
+      - name: Check Codespace Status and Keep Alive
+        run: |
+          CODESPACE_NAME="bookish-space-meme-4jvgq4xj494q3jwxp"
+          STATUS=$(gh codespace list --json name,state | jq -r --arg name "$CODESPACE_NAME" '.[] | select(.name == $name) | .state')
+
+          if [ -z "$STATUS" ]; then
+            echo "Error fetching codespace status or codespace does not exist."
+            exit 1
+          fi
+
+          echo "Codespace status: $STATUS"
+
+          if [ "$STATUS" == "Shutdown" ]; then
+            echo "Codespace is offline. Attempting to start it by SSH..."
+            gh codespace ssh --codespace $CODESPACE_NAME -- echo 'Codespace started!'
+          else
+            echo "Codespace is active. Sending keep-alive signal..."
+            gh codespace ssh --codespace $CODESPACE_NAME -- echo 'Keep-alive signal'
+          fi
+          
